### PR TITLE
Fix full version calc in push-images.sh

### LINKED ISSUE #53: Unable to push images to docker hub
Currently master builds failes with unable to deploy images to docker hub.

@mbrukman Any idea?

### PR DESCRIPTION
**Pull request by farodin91**
Fixes #53

Signed-off-by: Jan Jansen <jan.jansen@gdata.de>

### CODE REVIEW

File: push-images.sh [hunk 1]
```diff
@@ -26,8 +26,9 @@ latest_version=${versions[${#versions[@]}-1]}
 for v in "${versions[@]}"; do
   if [ -z "${version}" ] || [ "${version}" == "${v}" ]; then
     # read full version from Dockerfile
-    full_version=$(grep "ARG JANUS_VERSION" ${v}/Dockerfile | cut -d"=" -f 2)
+    full_version=$(grep "ARG JANUS_VERSION" ${v}/Dockerfile | cut -d"=" -f 2 | head -n 1)
```
Comment (FlorianHockmann) [inline push-images.sh:29]: Don't we have [the same problem](https://github.com/JanusGraph/janusgraph-docker/blob/480e44bd57657d114e01c5df75a13d334607ed3d/build-images.sh#L32) in `build-images.sh`?

Comment (farodin91) [reply push-images.sh:29]: It is already fixed in build-images.sh

Comment (FlorianHockmann) [reply push-images.sh:29]: D'OH, I just looked at the end of the line and therefore didn't see that it's placed there before the `cut`.
